import type { GeoClientContext } from './context.js';
import { requireFetch } from './context.js';

class GeoApiError extends Error {
  readonly _tag = 'GeoApiError';
}

export type GraphQlResponse<T> = {
  data?: T;
  errors?: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isHex(value: unknown): value is `0x${string}` {
  return typeof value === 'string' && /^0x[0-9a-fA-F]*$/.test(value);
}

function isAddress(value: unknown): value is `0x${string}` {
  return typeof value === 'string' && /^0x[0-9a-fA-F]{40}$/.test(value);
}

async function responseErrorMessage(response: Response): Promise<string> {
  let body = '';
  try {
    body = await response.text();
  } catch (_error) {}

  const status = `${response.status} ${response.statusText}`.trim();
  return body ? `${status}: ${body}` : status;
}

function responseOk(response: Response): boolean {
  if (typeof response.ok === 'boolean') return response.ok;
  if (typeof response.status === 'number') return response.status >= 200 && response.status < 300;
  return true;
}

/**
 * Sends a GraphQL request to the Geo API configured on the provided context.
 *
 * This low-level helper returns the full GraphQL envelope. Use
 * {@link graphqlData} when GraphQL `errors` or missing `data` should throw.
 *
 * @example
 * ```ts
 * const response = await geo.api.graphql<{
 *   entity: { id: string; name: string | null } | null;
 * }>(`
 *   query {
 *     entity(id: "3af3e22d21694a078681516710b7ecf1") {
 *       id
 *       name
 *     }
 *   }
 * `);
 *
 * if (response.errors) {
 *   console.error(response.errors);
 * }
 * ```
 *
 * @param context Client context containing the API origin and fetch implementation.
 * @param query GraphQL query string to send.
 * @returns The parsed GraphQL response envelope.
 * @throws When fetch fails, the HTTP response is not successful, or the response is not JSON.
 */
export async function graphqlRequest<T>(context: GeoClientContext, query: string): Promise<GraphQlResponse<T>> {
  const fetchFn = requireFetch(context, 'GraphQL requests');
  let result: Response;
  try {
    result = await fetchFn(`${context.network.apiOrigin}/graphql`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query }),
    });
  } catch (error) {
    throw new GeoApiError(`Could not fetch GraphQL data: ${error}`);
  }

  if (!responseOk(result)) {
    throw new GeoApiError(`GraphQL request failed: ${await responseErrorMessage(result)}`);
  }

  let response: unknown;
  try {
    response = await result.json();
  } catch (error) {
    throw new GeoApiError(`Could not parse GraphQL response: ${error}`);
  }

  if (!isRecord(response)) {
    throw new GeoApiError('GraphQL response must be an object');
  }

  return response as GraphQlResponse<T>;
}

/**
 * Sends a GraphQL request and returns only the `data` payload.
 *
 * This is the preferred helper for SDK workflows that need graph context. It
 * treats GraphQL `errors` and missing `data` as failures so callers do not
 * accidentally continue with empty successful results.
 *
 * @example
 * ```ts
 * const data = await graphqlData<{ entity: { id: string } | null }>(
 *   context,
 *   `query { entity(id: "3af3e22d21694a078681516710b7ecf1") { id } }`,
 * );
 * ```
 *
 * @param context Client context containing the API origin and fetch implementation.
 * @param query GraphQL query string to send.
 * @returns The typed GraphQL `data` payload.
 * @throws When the request fails, GraphQL returns errors, or no data is present.
 */
export async function graphqlData<T>(context: GeoClientContext, query: string): Promise<T> {
  const response = await graphqlRequest<T>(context, query);
  if (response.errors) {
    throw new GeoApiError(`GraphQL request returned errors: ${JSON.stringify(response.errors)}`);
  }
  if (response.data === undefined) {
    throw new GeoApiError('GraphQL response did not include data');
  }

  return response.data;
}

/**
 * Requests transaction calldata for a published edit from the configured Geo API.
 *
 * This is useful when calldata must be generated by an API service rather than
 * locally. For personal-space publish calldata, prefer
 * `geo.edits.publishToSpace(...)` or `geo.personalSpaces.publishEdit(...)`.
 *
 * @example
 * ```ts
 * const { to, data } = await geo.api.getEditCalldata({
 *   spaceId,
 *   cid: 'ipfs://bafkreihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku',
 * });
 *
 * await walletClient.sendTransaction({ to, data });
 * ```
 *
 * @param context Client context containing the API origin and fetch implementation.
 * @param params Space ID and edit CID to submit to the API.
 * @returns Target address and calldata returned by the API.
 * @throws When the request fails or the API response is malformed.
 */
export async function getEditCalldata(context: GeoClientContext, params: { spaceId: string; cid: string }) {
  const fetchFn = requireFetch(context, 'Edit calldata requests');
  let result: Response;
  try {
    result = await fetchFn(`${context.network.apiOrigin}/space/${params.spaceId}/edit/calldata`, {
      method: 'POST',
      body: JSON.stringify({ cid: params.cid }),
    });
  } catch (error) {
    throw new GeoApiError(`Could not get edit calldata from space ${params.spaceId}: ${error}`);
  }

  if (!responseOk(result)) {
    throw new GeoApiError(
      `Could not get edit calldata from space ${params.spaceId}: ${await responseErrorMessage(result)}`,
    );
  }

  let response: unknown;
  try {
    response = await result.json();
  } catch (error) {
    throw new GeoApiError(
      `Could not parse response from API when getting calldata for space ${params.spaceId}: ${error}`,
    );
  }

  if (!isRecord(response) || !isAddress(response.to) || !isHex(response.data)) {
    throw new GeoApiError(`Malformed edit calldata response for space ${params.spaceId}`);
  }

  return {
    to: response.to,
    data: response.data,
  };
}
